### ISSUE TITLE
Surge.For.Mac.5.3.1-2379.Full.Patched.dmg版本无法打开

### ISSUE THREAD

**Issue by suxj22** [LanYunDev/InjectLib_bak#2]
MacOS 14.0版本，下载该版本后无法打开，崩溃报告如下：
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Surge [28493]
Path:                  /Volumes/*/Surge.app/Contents/MacOS/Surge
Identifier:            com.nssurge.surge-mac
Version:               5.3.1 (2379)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-08-22 16:14:35.2148 +0800
OS Version:            macOS 14.0 (23A5312d)
Report Version:        12
Anonymous UUID:        C937EF63-5CDA-2407-55A3-CE42A7AEC5FF

Sleep/Wake UUID:       4A5BE54C-3872-41B0-80B2-2AC46366860C

Time Awake Since Boot: 34000 seconds
Time Since Wake:       2771 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/Bugsnag.framework/Versions/A/Bugsnag
Referenced from: <C4006531-D0F2-3252-8EEA-BCE53794C6B1> /Volumes/*/Surge.app/Contents/MacOS/Surge
Reason: tried: '/Volumes/Surge For Mac 5.3.1-2379 Full Patched/Surge.app/Contents/Frameworks/Bugsnag.framework/Versions/A/Bugsnag' (code signature in <9EAE454D-8523-3B48-8DB3-B58352906945> '/Volumes/Surge For Mac 5.3.1-2379 Full Patched/Surge.app/Contents/Frameworks/Bugsnag.framework/Versions/A/Bugsnag' not valid for use in process: Trying to load an unsigned library), '/Volumes/Surge For Mac 5.3.1-2379 Full Patched/Surge.app/Contents/Frameworks/Bugsnag.framework/Versions/A/Bugsnag' (code signature in <9EAE454D-8523-3B48-8DB3-B58352906945> '/Volumes/Surge For Mac 5.3.1-2379 Full Patched/Surge.app/Contents/Frameworks/Bugsnag.framework/Versions/A/Bugsnag' not valid for use in process: Trying to load an unsigned library), '/System/Library/Frameworks/Bugsnag.framework/Versions/A/Bugsnag' (no such file, not in dyld
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x18a73db48 __abort_with_payload + 8
1   dyld                          	       0x18a74a108 abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x18a74a13c abort_with_payload + 16
3   dyld                          	       0x18a6d1518 dyld4::halt(char const*, dyld4::StructuredError const*) + 304
4   dyld                          	       0x18a6ce1e8 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3884
5   dyld                          	       0x18a6ccf44 start + 1948

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016d42e920   x3: 0x000000000000008e
    x4: 0x000000016d42e520   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x000000016d42e48f  x10: 0x000000000000000a  x11: 0x0000000000000000
   x12: 0x0000000000000032  x13: 0x1000000000000000  x14: 0x0000000000000004  x15: 0x0000000000008000
   x16: 0x0000000000000209  x17: 0x000000018a6ca37c  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016d42e520  x21: 0x000000000000008e  x22: 0x000000016d42e920  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x000000016d42f368  x26: 0x000000016d42f2a8  x27: 0x0000000000000000
   x28: 0x000000001f070004   fp: 0x000000016d42e4f0   lr: 0x000000018a74a108
    sp: 0x000000016d42e4b0   pc: 0x000000018a73db48 cpsr: 0x80001000
   far: 0x00000001035b8000  esr: 0x56000080  Address size fault

Binary Images:
       0x103588000 -        0x10359bfff com.diephouse.matt.MMMarkdown (1.0) <e26fee4b-77d3-3471-a034-5efd3d03c8bc> /Volumes/*/Surge.app/Contents/Frameworks/MMMarkdown.framework/Versions/A/MMMarkdown
       0x1029d0000 -        0x102fb7fff com.nssurge.surge-mac (5.3.1) <c4006531-d0f2-3252-8eea-bce53794c6b1> /Volumes/*/Surge.app/Contents/MacOS/Surge
       0x18a6c7000 -        0x18a75a86f dyld (*) <197a2824-ba58-3ff4-8c52-399ae7ba8457> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=890.3M resident=0K(0%) swapped_out_or_unallocated=890.3M(100%)
Writable regions: Total=12.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=12.3M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__DATA                             475K        4 
__DATA_CONST                       486K        3 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       883.8M        3 
__TEXT                            6720K        3 
dyld private memory               4384K        4 
shared memory                       32K        1 
===========                     =======  ======= 
TOTAL                            959.6M       22 

-----------
Full Report
-----------

{"app_name":"Surge","timestamp":"2023-08-22 16:14:35.00 +0800","app_version":"5.3.1","slice_uuid":"c4006531-d0f2-3252-8eea-bce53794c6b1","build_version":"2379","platform":1,"bundleID":"com.nssurge.surge-mac","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.0 (23A5312d)","roots_installed":0,"name":"Surge","incident_id":"BE8C7342-99CA-4466-8FA7-FCC3AC2BA2E1"}
{
  "uptime" : 34000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,1",
  "coalitionID" : 4443,
  "osVersion" : {
    "train" : "macOS 14.0",
    "build" : "23A5312d",
    "releaseType" : "User"
  },
  "captureTime" : "2023-08-22 16:14:35.2148 +0800",
  "codeSigningMonitor" : 1,
  "incident" : "BE8C7342-99CA-4466-8FA7-FCC3AC2BA2E1",
  "pid" : 28493,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-08-22 16:14:35.1670 +0800",
  "procStartAbsTime" : 833278048463,
  "procExitAbsTime" : 833279187229,
  "procName" : "Surge",
  "procPath" : "\/Volumes\/*\/Surge.app\/Contents\/MacOS\/Surge",
  "bundleInfo" : {"CFBundleShortVersionString":"5.3.1","CFBundleVersion":"2379","CFBundleIdentifier":"com.nssurge.surge-mac"},
  "storeInfo" : {"deviceIdentifierForVendor":"AE6200AA-8334-52B5-B899-671638C91C14","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.nssurge.surge-mac",
  "crashReporterKey" : "C937EF63-5CDA-2407-55A3-CE42A7AEC5FF",
  "codeSigningID" : "com.nssurge.surge-mac",
  "codeSigningTeamID" : "YCKFLA6N72",
  "codeSigningFlags" : 570520337,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"NAEAANQAAAAQAQAAGAEAACABAAAoAQAAMAEAAEwBAAAwQYDSARAA1A==","atPC":"AwEAVH8jA9X9e7+p\/QMAkcww\/pe\/AwCR\/XvBqP8PX9bAA1\/WEC2A0g=="},
  "wakeTime" : 2771,
  "sleepWakeUUID" : "4A5BE54C-3872-41B0-80B2-2AC46366860C",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @rpath\/Bugsnag.framework\/Versions\/A\/Bugsnag","Referenced from: <C4006531-D0F2-3252-8EEA-BCE53794C6B1> \/Volumes\/*\/Surge.app\/Contents\/MacOS\/Surge","Reason: tried: '\/Volumes\/Surge For Mac 5.3.1-2379 Full Patched\/Surge.app\/Contents\/Frameworks\/Bugsnag.framework\/Versions\/A\/Bugsnag' (code signature in <9EAE454D-8523-3B48-8DB3-B58352906945> '\/Volumes\/Surge For Mac 5.3.1-2379 Full Patched\/Surge.app\/Contents\/Frameworks\/Bugsnag.framework\/Versions\/A\/Bugsnag' not valid for use in process: Trying to load an unsigned library), '\/Volumes\/Surge For Mac 5.3.1-2379 Full Patched\/Surge.app\/Contents\/Frameworks\/Bugsnag.framework\/Versions\/A\/Bugsnag' (code signature in <9EAE454D-8523-3B48-8DB3-B58352906945> '\/Volumes\/Surge For Mac 5.3.1-2379 Full Patched\/Surge.app\/Contents\/Frameworks\/Bugsnag.framework\/Versions\/A\/Bugsnag' not valid for use in process: Trying to load an unsigned library), '\/System\/Library\/Frameworks\/Bugsnag.framework\/Versions\/A\/Bugsnag' (no such file, not in dyld"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":455865,"threadState":{"x":[{"value":6},{"value":1},{"value":6128068896},{"value":142},{"value":6128067872},{"value":0},{"value":0},{"value":0},{"value":32},{"value":6128067727},{"value":10},{"value":0},{"value":50},{"value":1152921504606846976},{"value":4},{"value":32768},{"value":521},{"value":6617342844,"symbolLocation":416,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6128067872},{"value":142},{"value":6128068896},{"value":1},{"value":6},{"value":6128071528},{"value":6128071336},{"value":0},{"value":520552452}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6617866504},"cpsr":{"value":2147487744},"fp":{"value":6128067824},"sp":{"value":6128067760},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6617815880,"matchesCrashFrame":1},"far":{"value":4351295488}},"frames":[{"imageOffset":486216,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":2},{"imageOffset":536840,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":2},{"imageOffset":536892,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":2},{"imageOffset":42264,"symbol":"dyld4::halt(char const*, dyld4::StructuredError const*)","symbolLocation":304,"imageIndex":2},{"imageOffset":29160,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3884,"imageIndex":2},{"imageOffset":24388,"symbol":"start","symbolLocation":1948,"imageIndex":2}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4351098880,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.diephouse.matt.MMMarkdown",
    "size" : 81920,
    "uuid" : "e26fee4b-77d3-3471-a034-5efd3d03c8bc",
    "path" : "\/Volumes\/*\/Surge.app\/Contents\/Frameworks\/MMMarkdown.framework\/Versions\/A\/MMMarkdown",
    "name" : "MMMarkdown",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4338810880,
    "CFBundleShortVersionString" : "5.3.1",
    "CFBundleIdentifier" : "com.nssurge.surge-mac",
    "size" : 6193152,
    "uuid" : "c4006531-d0f2-3252-8eea-bce53794c6b1",
    "path" : "\/Volumes\/*\/Surge.app\/Contents\/MacOS\/Surge",
    "name" : "Surge",
    "CFBundleVersion" : "2379"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6617329664,
    "size" : 604272,
    "uuid" : "197a2824-ba58-3ff4-8c52-399ae7ba8457",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6616580096,
  "size" : 3971661824,
  "uuid" : "411c6161-39d1-33b8-830d-c90b3e51ed0a"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=890.3M resident=0K(0%) swapped_out_or_unallocated=890.3M(100%)\nWritable regions: Total=12.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=12.3M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__DATA                             475K        4 \n__DATA_CONST                       486K        3 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       883.8M        3 \n__TEXT                            6720K        3 \ndyld private memory               4384K        4 \nshared memory                       32K        1 \n===========                     =======  ======= \nTOTAL                            959.6M       22 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "dbc492282a4c7a0fc385c618afbf252dadb56506",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6112d17137f5d11121dcd4e2",
      "factorPackIds" : {

      },
      "deploymentId" : 250000358
    },
    {
      "rolloutId" : "6246d6a916a70b047e454124",
      "factorPackIds" : {

      },
      "deploymentId" : 240000010
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "6dd670af-0633-45e4-ae5f-122ae4df02be",
      "experimentId" : "64406ba83deb637ac8a04419",
      "deploymentId" : 900000017
    },
    {
      "treatmentId" : "b24f3a71-087b-4e29-ba8d-dbc0ef744d12",
      "experimentId" : "64bd0307084d03725ee431f6",
      "deploymentId" : 500000001
    }
  ]
}
}

Model: MacBookPro18,1, BootROM 10151.0.305.0.1, proc 10:8:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Samsung
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Jul 26 2023 02:31:55 version 20.10.1062.0.8.7.159 FWID 01-e1f06d5a
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by LanYunDev** [comment]
打不开就运行一键脚本.
https://github.com/QiuChenlyOpenSource/InjectLib/tree/main/Surge一键脚本
